version: '3.9'
services:

  # docker-compose build
  # docker-compose run app sh -c "django-admin startproject app ."
  # docker-compose run app sh -c "python manage.py test && flake8"
  # docker-compose run app sh -c "python manage.py startapp core"
  # docker-compose run app sh -c "python manage.py makemigrations core"
  # docker-compose run --rm app sh -c "python manage.py startapp user"

  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres


  db:
  
    image: postgres:13.2-alpine

    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpostgres

    volumes:
      - ./app/postgres.conf:/etc/postgresql/postgresql.conf

    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    # restart: always


  pgadmin:
    
    container_name: pgadmin
    # dpage/pgadmin4:latest
    image: dpage/pgadmin4:latest

    environment: 
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - listen_addresses='*'

    ports:
      - "80:80"

  app:

    # Name of the container
    container_name: recipe-app-api

    # Restart policy
    restart: always

    # build : chemin pour le Dockerfile
    build: 
      context: .

    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

    # command: >
    #   bash -c "python manage.py migrate
    #   && python manage.py makemigrations polls
    #   && python manage.py migrate
    #   && python manage.py runserver 0.0.0.0:8000"

    # Routing des ports host:docker
    ports:
      - "8000:8000"

    # Environment
    environment:
    # Timezone
      # TZ: "America/Montreal"
      - TZ=America/Montreal
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpostgres

    # Shared file
    volumes:
      - ./app:/app

    # image: "python"

    depends_on:
      - db